### PR TITLE
Ctrl-Q from the main window quits the application

### LINKED ISSUE #61: Allow Ctrl+Q to quit
A convenience shortcut which every program ever seems to support. Use Ctrl+Q to quit the program

### PR DESCRIPTION
**Pull request by vurpo**
Fixes #61.

I've only tested this on my laptop running Fedora, but it seems simple enough.
Does macOS and its Command key need to be separately handled?

### CODE REVIEW

**Comment by Ralith** [comment]
Is there some reason not to use the more portable and configurable `QKeySequence::Quit` instead?

**Comment by vurpo** [comment]
That's a good question.

**Comment by vurpo** [comment]
Now it does (tested and still works the same)

**Comment by mujx** [comment]
Thanks! Btw cmd+Q already worked on macOS.

**Pull request merged**
