### PR TITLE
Add the packaging metadata to build the nheko snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest nheko in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

I'm trying hard to get all of my friends to use matrix. Having a desktop client in the Ubuntu store would help a lot. I took a look at yours and it's very pretty. Thanks for the work!

If you haven't heard about snaps before, there's a lot of info in https://snapcraft.io

To test this in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/nheko
    $ cd nheko
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

At this early stage of development, you can put it in the edge channel of the store, where it won't be visible for user searches, but it will be available for your early adopters and the ubuntu community of testers that will give you quick feedback as you make new releases. After you add the snapcraft.yaml in your repo, you can automate the continuous delivery every time you push something to master by just signing up in build.snapcraft.io

If you have any questions, please let me know.

pura vida.

**Comment by mujx** [comment]
Thanks for the interest in the project! I was planning to use snap for packaging, along with an AUR package. 

I will look a bit more into the docs, but I suppose snapcraft will support nheko.desktop or a way to provide a desktop icon.

**Comment by elopio** [comment]
Thanks for the review @mujx.
Take a look at https://snapcraft.io/docs/build-snaps/metadata#desktop-files

**Comment by mujx** [comment]
Is it possible to specify a Qt version other than the default one (with a ppa maybe?), because nheko requires Qt 5.7 or greater to work properly.

**Comment by elopio** [comment]
Sure you can @mujx. But you will have to use [launchpad or travis](https://snapcraft.io/docs/build-snaps/ci-integration) for continuous delivery, because PPAs are not yet supported in build.snapcraft.io.

Do you want me to make the change here?

**Comment by mujx** [comment]
@elopio Please do. You can use the PPA from [.ci/linux/install-deps.sh](https://github.com/mujx/nheko/blob/master/.ci/linux/install-deps.sh)

**Comment by gutigen** [comment]
I recommend ignoring Snaps which have no sandboxing outside of Ubuntu and focusing on a technology which won't share same faith as every other Canonical project (Upstart, Mir, Unity - all replaced by community agreed solution).

https://flatpak.org - backed by Red Hat which also pushed systemd, wayland and gnome which replaced Canonical technologies mentioned earlier. Don't waste time on soon obsolete tech.

**Comment by mujx** [comment]
@gutigen The snap has been removed because the required qt version wasn't supported. There is an AppImage currently and PRs for flatpak are welcome.

**Pull request merged**
