### PR TITLE
changed "Redact message" to "Delete message";

### PR DESCRIPTION
**Pull request by F1ash**
added "Edit message" for text messages;

### CODE REVIEW

**Comment by vurpo** [comment]
I don't think this should be merged as it is. MatrixClient is meant to represent the Matrix client API, but the API has no method for editing a message. It is misleading to make a method redact a message, but call it "edit".

**Comment by F1ash** [comment]
> I don't think this should be merged as it is. MatrixClient is meant to represent the Matrix client API, but the API has no method for editing a message. It is misleading to make a method redact a message, but call it "edit".
yes, it is not edit a message in usual sense... Can you advise how to name this method?

**Comment by vurpo** [comment]
Because Matrix has planned to add some way to update existing events (to make e.g. reactions, edits possible), I think this feature shouldn't be added until there is some spec way to do it for real. Otherwise you end up with different Matrix clients doing it in incompatible ways.

**Comment by F1ash** [comment]
Some offtop... 
Can i use for implement Quote message the format of "content" which used in [Riot](https://riot.im/):

image

**Comment by vurpo** [comment]
Nheko doesn't have any support for formatted messages yet, so I'm not sure about that. Also, they are currently developing a new machine-readable format for quoting/replying to messages (which is in riot develop IIRC), so it would be better to implement support for that instead, as soon as the format is finished.

**Comment by F1ash** [comment]
ok...

**Comment by mujx** [comment]
@F1ash You can go ahead and implement quotes & formatted text in general. The `formatted_body` property on the event should be parsed first tho. 

The event parsing is happening in the matrix-structs library.

**Comment by mujx** [comment]
Check #292

**Comment by F1ash** [comment]
Is dirty probe to implement Quote:
`
...
        QStringList msg_parts_;
        QString msg_body, quoted;

        switch (ty) {
        case mtx::events::MessageType::Text:
                if ( msg.startsWith(" > ") ) {
                    msg_body = msg;
                    msg_body.remove(" > ");
                    msg_parts_ = msg_body.split("\n\n", QString::KeepEmptyParts);
                    quoted = QString("<blockquote>\n<p>%1</p>\n</blockquote>\n<p>%2</p>\n")
                            .arg(msg_parts_.first()).arg(msg_parts_.last());
                    msg_body = QString(" > %1\n\n%2")
                            .arg(msg_parts_.first()).arg(msg_parts_.last());
                    body = {{"msgtype", "m.text"}, {"body", msg_body},
                            {"formatted_body", quoted}, {"format", "org.matrix.custom.html"}};
                } else {
                    body = {{"msgtype", "m.text"}, {"body", msg}};
                };
                break;
        case mtx::events::MessageType::Emote:
...
`

works good for Nheko and Riot... But i not sure  that is correctly for new (developing) features...

**Comment by mujx** [comment]
@F1ash Are you currently working on replies?

**Comment by F1ash** [comment]
> Are you currently working on replies?
No? at last time i have not a time for this. I have some questions about implementation Reply widget (and layout), and recursive included quotes\replies. But here that is not easy. Have a develop channel\conference for it?

**Pull request closed without merging**
