### PR TITLE
Add basic nix expressions

### PR DESCRIPTION
**Pull request by JaniM**
Allows `nix-build` for basic building and `nix-env -f . -i` for installing.

### CODE REVIEW

**Comment by JaniM** [comment]
I do not know what's up with the .gitignore diff

**Comment by mujx** [comment]
It's not really a problem. Could you update this to include the lmdb stuff?

**Comment by JaniM** [comment]
Done. Btw, this _should_ work on Darwin as well.

**Comment by mujx** [comment]
Thanks a lot! Could you also add some instructions on the readme for nix?

**Comment by JaniM** [comment]
It's finally proper.

**Pull request merged**
